# /serverless.yaml
service: nest-serverless-tutorial

frameworkVersion: '4'

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs20.x
  timeout: 60
  memorySize: 512
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_ID_1}
      - ${env:SUBNET_ID_2}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline

package:
  include:
    - rds-ca-bundle.pem
